set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property PACKAGE_PIN Y18 [get_ports Clk]

set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN B21 [get_ports reset_n]

#以太网gmii引脚分配
set_property PACKAGE_PIN V22 [get_ports eth_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports eth_reset_n]

set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[0]}]

set_property PACKAGE_PIN R19 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN P19 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN V18 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN V17 [get_ports {rgmii_rxd[0]}]

set_property PACKAGE_PIN Y22 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN W21 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN W22 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN U21 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxdv]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txen]
set_property PACKAGE_PIN AB18 [get_ports rgmii_rxdv]
set_property PACKAGE_PIN U22 [get_ports rgmii_tx_clk]
set_property PACKAGE_PIN AA19 [get_ports rgmii_txen]

set_property PACKAGE_PIN W19 [get_ports rgmii_rx_clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rx_clk_i]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ad_clk2_OBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rgmii_rx_clk_i]
#ADC引脚分配
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_db_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_busy_i]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_convst_o]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_cs_n_o]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_rd_n_o]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_reset_o]

set_property PACKAGE_PIN C19 [get_ports {ad7606_db_i[15]}]
set_property PACKAGE_PIN C18 [get_ports {ad7606_db_i[14]}]
set_property PACKAGE_PIN B18 [get_ports {ad7606_db_i[13]}]
set_property PACKAGE_PIN B17 [get_ports {ad7606_db_i[12]}]
set_property PACKAGE_PIN D16 [get_ports {ad7606_db_i[11]}]
set_property PACKAGE_PIN E16 [get_ports {ad7606_db_i[10]}]
set_property PACKAGE_PIN C17 [get_ports {ad7606_db_i[9]}]
set_property PACKAGE_PIN D17 [get_ports {ad7606_db_i[8]}]
set_property PACKAGE_PIN B16 [get_ports {ad7606_db_i[7]}]
set_property PACKAGE_PIN B15 [get_ports {ad7606_db_i[6]}]
set_property PACKAGE_PIN C15 [get_ports {ad7606_db_i[5]}]
set_property PACKAGE_PIN C14 [get_ports {ad7606_db_i[4]}]
set_property PACKAGE_PIN D15 [get_ports {ad7606_db_i[3]}]
set_property PACKAGE_PIN D14 [get_ports {ad7606_db_i[2]}]
set_property PACKAGE_PIN B13 [get_ports {ad7606_db_i[1]}]
set_property PACKAGE_PIN C13 [get_ports {ad7606_db_i[0]}]
set_property PACKAGE_PIN A16 [get_ports {ad7606_os_o[2]}]
set_property PACKAGE_PIN A13 [get_ports {ad7606_os_o[1]}]
set_property PACKAGE_PIN A14 [get_ports {ad7606_os_o[0]}]
set_property PACKAGE_PIN F13 [get_ports ad7606_busy_i]
set_property PACKAGE_PIN A15 [get_ports ad7606_convst_o]
set_property PACKAGE_PIN F14 [get_ports ad7606_cs_n_o]
set_property PACKAGE_PIN A18 [get_ports ad7606_rd_n_o]
set_property PACKAGE_PIN A19 [get_ports ad7606_reset_o]

#LED灯
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN M22 [get_ports {led[0]}]
set_property PACKAGE_PIN N22 [get_ports {led[1]}]


